apiVersion: v1
kind: Pod
metadata:
  name: mysql-2
spec:
  volumes:
    - name: pv-storage
      persistentVolumeClaim:
        claimName: dynamic-pvc
  containers:
    - name: mysql-2
      image: mysql:8.0
      env:
      - name: MYSQL_ROOT_PASSWORD
        value: password
      volumeMounts:
        - mountPath: "/var/lib/mysql"
          name: pv-storage
