apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dynamic-pvc
spec:
# Not specified any storage class to pick up the default storage class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi