apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql 
  serviceName: mysql-headless
  replicas: 2
  template:                             # Same as the mysql pod which had created earlier
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: password        
        volumeMounts:
        - name: mysql
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: mysql                        # Prefix for the PVC name. PVC name will be <metadata-name>-<pod-name>
    spec:
      accessModes: [ "ReadWriteOnce" ]   # Volume can be read and written only by one node.
      resources:
        requests:
          storage: 1Gi
