# Headless Service
apiVersion: v1
kind: Service
metadata:
  name: mysql-headless
spec:
  ports:
  - port: 3306
  clusterIP: None   # Indicates Headless Service
  selector:
    app: mysql        # Route traffic to pod with app:sts label
